version: '3'
services:
  trustart:
    environment:
      temporary_folder: 'temp'
    image: trustart-humberto
    build: .
    container_name: cont-trustart-humberto
    command: /bin/bash -c "pipenv run python app/manage.py"
    volumes:
      - .:/trustart/